// Generated by dia2code
#ifndef STATE__ANTIDOTE__H
#define STATE__ANTIDOTE__H

#include <string>

namespace state {
  class Character;
  class Item;
}

#include "Character.h"
#include "Item.h"

namespace state {

  /// class Antidote - 
  class Antidote : public state::Item {
    // Operations
  public:
    void CureStatus (Character character);
    Antidote (std::string name);
    ~Antidote ();
    // Setters and Getters
  };

};

#endif
