// Generated by dia2code
#ifndef STATE__ASSASSIN__H
#define STATE__ASSASSIN__H

#include <string>

namespace state {
  class Character;
  class Hero;
}

#include "Character.h"
#include "Hero.h"

namespace state {

  /// class Assassin - 
  class Assassin : public state::Hero {
    // Attributes
  public:
    std::string name;
    // Operations
  public:
    void Stab (Character character1, Character character2);
    void Poison (Character character1, Character character2, int time_passed);
    void darkMagik (int character1, Character character2);
    void attack (Character character1);
    Assassin (int life, int att, int spd, int crit, int def, std::string name);
    ~Assassin ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
