// Generated by dia2code
#ifndef STATE__BLOB__H
#define STATE__BLOB__H

#include <string>

namespace state {
  class Character;
  class Monsters;
}

#include "Character.h"
#include "Monsters.h"

namespace state {

  /// class Blob - 
  class Blob : public state::Monsters {
    // Attributes
  private:
    std::string name;
    // Operations
  public:
    void sabot (Character character);
    void attack (Character character1);
    Blob (int life, int att, int def, int spd, int crit, std::string name);
    ~Blob ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
