// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <vector>
#include <string>

namespace state {
  class MobileElements;
}

#include "MobileElements.h"

namespace state {

  /// class Character - 
  class Character : public state::MobileElements {
    // Attributes
  public:
    int Life;
    int ATT;
    int DEF;
    int SPD;
    int Crit;
    int LifeMAX;
    std::vector<int> State;
    std::string name;
    // Operations
  public:
    Character (int life, int att, int spd, int crit, int def, std::string name);
    ~Character ();
    int getLife ();
    int getLifeMAX ();
    int getATT ();
    int getDEF ();
    int getSPD ();
    int getCrit ();
    std::vector<int> getState ();
    void setLife (int i);
    void setATT (int i);
    void setDEF (int i);
    void setSPD (int i);
    void setCrit (int i);
    void addState (int newState);
    void clearState (int oldState);
    void changeState (int newState);
    Character ();
    std::string getName ();
    void setName (std::string newName);
    bool isMonster ();
    // Setters and Getters
  };

};

#endif
