// Generated by dia2code
#ifndef STATE__DARKKNIGHT__H
#define STATE__DARKKNIGHT__H

#include <string>

namespace state {
  class Character;
  class Monsters;
}

#include "Character.h"
#include "Monsters.h"

namespace state {

  /// class DarkKnight - 
  class DarkKnight : public state::Monsters {
    // Attributes
  private:
    std::string name;
    // Operations
  public:
    void defend (Character character1, Character darkKnight_character);
    void heavyAttack (Character character1, Character character);
    void sabot (Character character);
    void attack (Character character1);
    DarkKnight (int life, int att, int spd, int crit, int def, std::string name);
    ~DarkKnight ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
