// Generated by dia2code
#ifndef STATE__DRAGON__H
#define STATE__DRAGON__H

#include <string>

namespace state {
  class Character;
  class Monsters;
}

#include "Character.h"
#include "Monsters.h"

namespace state {

  /// class Dragon - 
  class Dragon : public state::Monsters {
    // Attributes
  private:
    bool boss     = true;
    std::string name;
    // Operations
  public:
    void heavyAttack (Character character1, Character character2);
    void feu (Character character1, Character character2);
    void sabot (Character character);
    void attack (Character character1);
    Dragon (int life, int att, int spd, int crit, int def, std::string name);
    ~Dragon ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
