// Generated by dia2code
#ifndef STATE__DUNGEON__H
#define STATE__DUNGEON__H

#include <string>
#include <vector>

namespace state {
  class StaticElements;
}

#include "StaticElements.h"

namespace state {

  /// class Dungeon - 
  class Dungeon : public state::StaticElements {
    // Attributes
  protected:
    std::vector<std::string> mapNames;
    // Operations
  public:
    Dungeon ();
    ~Dungeon ();
    Dungeon (std::vector<std::string> maps);
    // Setters and Getters
    const std::vector<std::string>& getMapNames() const;
    void setMapNames(const std::vector<std::string>& mapNames);
  };

};

#endif
