// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <stdlib.h>
#include <vector>
#include <string>

namespace state {
  class Element;
  class Observable;
}

#include "Observable.h"
#include "Element.h"

namespace state {

  /// class ElementTab - 
  class ElementTab : public state::Observable {
    // Associations
    // Attributes
  private:
    size_t width;
    size_t height;
    std::vector<Element*> listElements;
    std::vector<std::string> listClassNames;
    // Operations
  public:
    size_t add (Element* e, std::string elementType);
    Element* get (int i, int j);
    ElementTab (size_t height, size_t width);
    ElementTab ();
    std::string getElementType (int i);
    uint getSize ();
    Element* Operator (int i, int j);
    // Setters and Getters
  };

};

#endif
