// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {

  /// class Element - 
  class Element {
    // Attributes
  public:
    bool staticElement;
    // Operations
  public:
    Element (bool isstat);
    ~Element ();
    // Setters and Getters
  };

};

#endif
