// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <stdlib.h>
#include <vector>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    // Attributes
  private:
    size_t width;
    size_t height;
    std::vector<Element*> list;
    // Operations
  public:
    size_t add (Element* e);
    Element* get (int i, int j);
    ElementTab (size_t height, size_t width);
    // Setters and Getters
  };

};

#endif
