// Generated by dia2code
#ifndef STATE__HERO__H
#define STATE__HERO__H

#include <string>

namespace state {
  class Character;
}

#include "Character.h"

namespace state {

  /// class Hero - 
  class Hero : public state::Character {
    // Attributes
  protected:
    bool ishero     = true;
    // Operations
  public:
    Hero ();
    ~Hero ();
    bool isMonster ();
    Hero (int life, int att, int spd, int crit, int def, std::string name);
    // Setters and Getters
    bool getIshero() const;
    void setIshero(bool ishero);
  };

};

#endif
