// Generated by dia2code
#ifndef STATE__ITEM__H
#define STATE__ITEM__H

#include <string>

namespace state {
  class StaticElements;
}

#include "StaticElements.h"

namespace state {

  /// class Item - 
  class Item : public state::StaticElements {
    // Attributes
  protected:
    std::string name;
    // Operations
  public:
    Item (std::string name);
    ~Item ();
    std::string getName ();
    void setName (std::string name);
    // Setters and Getters
  };

};

#endif
