// Generated by dia2code
#ifndef STATE__MAGE__H
#define STATE__MAGE__H

#include <string>

namespace state {
  class Character;
  class Hero;
}

#include "Character.h"
#include "Hero.h"

namespace state {

  /// class Mage - 
  class Mage : public state::Hero {
    // Attributes
  public:
    std::string name;
    // Operations
  public:
    void heal (Character character);
    void Fire (Character character1, Character character2);
    void darkMagic (Character character1, Character character2);
    void attack (Character character1);
    Mage (int life, int att, int spd, int crit, int def, std::string name);
    ~Mage ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
