// Generated by dia2code
#ifndef STATE__POTIONSOIN__H
#define STATE__POTIONSOIN__H

#include <string>

namespace state {
  class Character;
  class Item;
}

#include "Character.h"
#include "Item.h"

namespace state {

  /// class PotionSoin - 
  class PotionSoin : public state::Item {
    // Attributes
  public:
    int Regen;
    // Operations
  public:
    void soigner (Character character, int Regen);
    PotionSoin (int i, std::string name);
    ~PotionSoin ();
    // Setters and Getters
  };

};

#endif
