// Generated by dia2code
#ifndef STATE__POTIONVIE__H
#define STATE__POTIONVIE__H

#include <string>

namespace state {
  class Character;
  class Item;
}

#include "Character.h"
#include "Item.h"

namespace state {

  /// class PotionVie - 
  class PotionVie : public state::Item {
    // Attributes
  public:
    int RegenVie;
    // Operations
  public:
    void resurrect (Character character, int RegenVie);
    PotionVie (int i, std::string name);
    ~PotionVie ();
    // Setters and Getters
  };

};

#endif
