// Generated by dia2code
#ifndef STATE__RANGE__H
#define STATE__RANGE__H

#include <string>

namespace state {
  class Character;
  class Hero;
}

#include "Character.h"
#include "Hero.h"

namespace state {

  /// class Range - 
  class Range : public state::Hero {
    // Attributes
  public:
    std::string name;
    // Operations
  public:
    void Defend (Character character1, Character character2);
    void shoot (Character character1, Character character2);
    void sabot (Character character);
    void attack (Character character1);
    Range (int life, int att, int spd, int crit, int def, std::string name);
    ~Range ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
