// Generated by dia2code
#ifndef STATE__ROOM__H
#define STATE__ROOM__H


namespace state {
  class Team;
  class Dungeon;
}

#include "Dungeon.h"
#include "Team.h"

namespace state {

  /// class Room - 
  class Room : public state::Dungeon {
    // Associations
    // Attributes
  private:
    Team* heroTeam;
    Team* monsterTeam;
    bool bossRoom;
    // Operations
  public:
    Room (Team* heroTeam, Team* monsterTeam);
    ~Room ();
    Team* getHeroTeam ();
    void setHeroTeam (Team* newTeam);
    Team* getMonsterTeam ();
    void setMonsterTeam (Team* newTeam);
    bool isBossRoom ();
    // Setters and Getters
  };

};

#endif
