// Generated by dia2code
#ifndef STATE__SORCERER__H
#define STATE__SORCERER__H

#include <string>

namespace state {
  class Character;
  class Monsters;
}

#include "Character.h"
#include "Monsters.h"

namespace state {

  /// class Sorcerer - 
  class Sorcerer : public state::Monsters {
    // Attributes
  public:
    std::string name;
    // Operations
  public:
    void darkMagik (Character character1, Character character2);
    void poison (Character character1, Character character2, int time_passed_int);
    void feu (Character character1, Character character2);
    void attack (Character character1);
    Sorcerer (int life, int att, int spd, int crit, int def, std::string name);
    ~Sorcerer ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
