// Generated by dia2code
#ifndef STATE__STATICELEMENTS__H
#define STATE__STATICELEMENTS__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class StaticElements - 
  class StaticElements : public state::Element {
    // Attributes
  public:
    bool building;
    bool staticElement     = true;
    // Operations
  public:
    bool isStatic ();
    bool isBuilding ();
    StaticElements (bool building);
    ~StaticElements ();
    // Setters and Getters
  };

};

#endif
