// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
  class Observable;
}

#include "Observable.h"
#include "ElementTab.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  private:
    ElementTab* grid;
    ElementTab* chars;
    int spd_characters;
    int epoch;
    int epoch_rate;
    int dungeon_count;
    // Operations
  public:
    ElementTab* getGrid (ElementTab* grid);
    ElementTab* getChar (ElementTab* chars);
    State ();
    ~State ();
    // Setters and Getters
  };

};

#endif
