// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {
  class Event;
}

#include "StateEventId.h"
#include "Event.h"

namespace state {

  /// class StateEvent - 
  class StateEvent : public state::Event {
    // Attributes
  public:
    StateEventId stateEventid;
    // Operations
  public:
    StateEvent ();
    ~StateEvent ();
    // Setters and Getters
  };

};

#endif
