// Generated by dia2code
#ifndef STATE__TABEVENT__H
#define STATE__TABEVENT__H


namespace state {
  class Event;
  class ElementTab;
}

#include "EventTypeId.h"
#include "Event.h"
#include "ElementTab.h"

namespace state {

  /// class TabEvent - 
  class TabEvent : public state::Event {
    // Associations
    // Operations
  public:
    TabEvent ();
    ~TabEvent ();
    EventTypeId getEventType ();
    // Setters and Getters
  };

};

#endif
