// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H

#include <string>

namespace state {
  class Character;
  class Hero;
}

#include "Character.h"
#include "Hero.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Hero {
    // Attributes
  public:
    std::string name;
    // Operations
  public:
    void heavyAttack (Character character1, Character character2);
    void Defend (Character character1, Character character2);
    void attack (Character character1);
    Tank (int life, int att, int spd, int crit, int def, std::string name);
    ~Tank ();
    std::string getName ();
    void setName (std::string newName);
    // Setters and Getters
  };

};

#endif
