// Generated by dia2code
#ifndef STATE__TEAM__H
#define STATE__TEAM__H

#include <vector>

namespace state {
  class Character;
}

#include "Character.h"

namespace state {

  /// class Team - 
  class Team {
    // Associations
    // Attributes
  public:
    std::vector<Character*> ListPerso;
    // Operations
  public:
    bool isHeroTeam ();
    Team (std::vector<Character*> listPerso);
    ~Team ();
    std::vector<Character*> getTeam ();
    void setTeam (std::vector<Character*> team);
    void addToTeam (Character* character);
    void removeFromTeam (Character* character);
    Team ();
    // Setters and Getters
  };

};

#endif
