// Generated by dia2code
#ifndef STATE__VILLAGE__H
#define STATE__VILLAGE__H


namespace state {
  class Inventory;
  class Tavern;
  class Shop;
  class Team;
  class StaticElements;
}

#include "StaticElements.h"
#include "Inventory.h"
#include "Team.h"

namespace state {

  /// class Village - 
  class Village : public state::StaticElements {
    // Associations
    // Attributes
  public:
    Inventory* ListItems;
    int Money;
    Tavern* tavern;
    Shop* shop;
    Team* team;
    // Operations
  public:
    void mchurch ();
    void mcarriage (Team* team);
    Village (Tavern* tavern, Shop* shop, int money, Inventory* inventory, Team* team);
    ~Village ();
    void mtavern ();
    // Setters and Getters
  };

};

#endif
