// Generated by dia2code
#ifndef RENDER__DUNGEONDISPLAY__H
#define RENDER__DUNGEONDISPLAY__H

#include <string>
#include <vector>

namespace state {
  class Element;
  class Dungeon;
}

#include "state/Dungeon.h"

namespace render {

  /// class DungeonDisplay - 
  class DungeonDisplay {
    // Associations
    // Attributes
  public:
    std::string displayText     = "Choose your Dungeon";
    std::vector<std::string> listElementsinDungeon;
    sf::Font font;
    std::string dungeonList;
    // Operations
  public:
    std::vector<std::string> getDungeonImages ();
    void getFont ();
    DungeonDisplay ();
    DungeonDisplay (state::Element* e);
    ~DungeonDisplay ();
    std::string getDisplayText ();
    std::string getDungeonList ();
    void setDungeonList (std::string newList);
    // Setters and Getters
  };

};

#endif
