// Generated by dia2code
#ifndef RENDER__ELEMENTTABLAYER__H
#define RENDER__ELEMENTTABLAYER__H

#include <string>

namespace state {
  class ElementTab;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/ElementTab.h"

namespace render {

  /// class ElementTabLayer - 
  class ElementTabLayer : public render::Layer {
    // Associations
    // Attributes
  public:
    state::ElementTab* elementTab;
    std::string title;
    // Operations
  public:
    ElementTabLayer (state::ElementTab* elementTab);
    ~ElementTabLayer ();
    void initSurface ();
    state::ElementTab* getElementTabNames ();
    void setElementTab (state::ElementTab* newElementTabNames);
    void getElementTabTextures ();
    void setTitle (std::string title);
    std::string getTitle ();
    // Setters and Getters
  };

};

#endif
