// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <vector>

namespace render {
  class Surface;
  class ShopDisplay;
  class VillageDisplay;
  class TavernDisplay;
  class RoomDisplay;
}

#include "ShopDisplay.h"
#include "VillageDisplay.h"
#include "TavernDisplay.h"
#include "RoomDisplay.h"
#include "Surface.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    std::vector<Surface*> surface;
    std::vector<std::pair<uint,uint>> coords;
    // Operations
  public:
    Layer ();
    ~Layer ();
    Surface* getSurface (int i);
    void setSurface (Surface* surface);
    void initSurface ();
    void printText ();
    std::vector<Surface*> getSurfaceList ();
    void addCoords (std::pair<uint,uint> coords);
    // Setters and Getters
    const std::vector<std::pair<uint,uint>>& getCoords() const;
    void setCoords(const std::vector<std::pair<uint,uint>>& coords);
  };

};

#endif
