// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <SFML/Graphics.hpp>

namespace render {
  class ElementTabLayer;
  class StateLayer;
};
namespace state {
  class State;
  class Observer;
}

#include "state/State.h"
#include "state/Observer.h"
#include "ElementTabLayer.h"
#include "StateLayer.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  public:
    ElementTabLayer* tabLayer;
    StateLayer* stateLayer;
    state::State state;
    // Operations
  public:
    Scene (state::State* state);
    void stateChanged (state::Event* e);
    void draw (sf::RenderWindow* window);
    // Setters and Getters
  };

};

#endif
