// Generated by dia2code
#ifndef RENDER__SHOPDISPLAY__H
#define RENDER__SHOPDISPLAY__H

#include <string>
#include <vector>

namespace state {
  class Inventory;
}

#include "state/Inventory.h"

namespace render {

  /// class ShopDisplay - 
  class ShopDisplay {
    // Associations
    // Attributes
  public:
    std::vector<std::string> listElementsinShop     = {"marchand.jpg","money.png","box.png"};
    std::vector<std::pair<uint,uint>> listposElements;
    state::Inventory* inventory;
    state::Inventory* shopinventory;
    sf::Font font;
    // Operations
  public:
    ShopDisplay (state::Inventory* inventory, state::Inventory* shopInventory);
    ~ShopDisplay ();
    void getFont ();
    std::vector<std::string> getShopImages ();
    // Setters and Getters
  };

};

#endif
