// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H


namespace state {
  class State;
};
namespace render {
  class Layer;
}

#include "state/State.h"
#include "Layer.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer {
    // Associations
    // Attributes
  public:
    state::State state;
    // Operations
  public:
    StateLayer (state::State& state);
    ~StateLayer ();
    void initSurface ();
    // Setters and Getters
  };

};

#endif
