// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
  class VertexArray;
  class Drawable;
  class Transformable;
}


namespace render {

  /// class Surface - 
  class Surface : public sf::Drawable, public sf::Transformable {
    // Attributes
  public:
    sf::Texture texture;
    sf::VertexArray quads;
    uint height;
    uint width;
    uint wSize;
    uint hSize;
    sf::Font font ;
    sf::Sprite sprite;
    // Operations
  public:
    void loadTexture (std::string image_txt);
    void initQuads (int count);
    void setSpriteLocation (int x, int y, int i);
    void setSpriteTexture (int i);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    Surface (uint width, uint height, uint wSize, uint hSize);
    ~Surface ();
    sf::Texture getTexture ();
    void setTexture (sf::Texture newTexture);
    sf::VertexArray getQuads ();
    void setQuads (sf::VertexArray newQuad);
    void setFont (sf::Font font);
    void setSprite ();
    sf::Sprite getSprite ();
    void spriteSetScale (float x, float y);
    // Setters and Getters
  };

};

#endif
