// Generated by dia2code
#ifndef RENDER__TAVERNDISPLAY__H
#define RENDER__TAVERNDISPLAY__H


namespace state {
  class ElementTab;
  class Team;
}

#include "state/ElementTab.h"
#include "state/Team.h"

namespace render {

  /// class TavernDisplay - 
  class TavernDisplay {
    // Associations
    // Operations
  public:
    state::ElementTab getTavern ();
    state::Team getTeam ();
    // Setters and Getters
  };

};

#endif
