// Generated by dia2code
#ifndef RENDER__VILLAGEDISPLAY__H
#define RENDER__VILLAGEDISPLAY__H

#include <string>
#include <vector>

namespace state {
  class Team;
}

#include "state/Team.h"

namespace render {

  /// class VillageDisplay - 
  class VillageDisplay {
    // Associations
    // Attributes
  public:
    std::string displayText     = "Welcome to the Village";
    std::vector<std::string> listElementsinVillage     = {"res/village.jpg","res/money.png"};
    sf::Font font;
    // Operations
  public:
    std::vector<std::string> getVillageImages ();
    void getFont ();
    VillageDisplay ();
    ~VillageDisplay ();
    std::string getDisplayText ();
    // Setters and Getters
  };

};

#endif
