// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <string>
#include <vector>

namespace engine {
  class Engine;
};
namespace state {
  class State;
}

#include "state/State.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  protected:
    engine::Engine* engine;
    state::State* state;
    // Operations
  public:
    void run (std::vector<std::string>& list);
    AI ();
    ~AI ();
    // Setters and Getters
    const engine::Engine*& getEngine() const;
    void setEngine(const engine::Engine*& engine);
    const state::State*& getState() const;
    void setState(const state::State*& state);
  };

};

#endif
