// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <string>
#include <vector>

namespace engine {
  class Engine;
}

#include "engine/Engine.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  public:
    engine::Engine engine;
    // Operations
  public:
    std::string run (std::vector<std::string>& list);
    AI ();
    ~AI ();
    // Setters and Getters
  };

};

#endif
