// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <string>
#include <vector>

namespace state {
  class State;
};
namespace ai {
  class AI;
};
namespace state {
  class Room;
};
namespace ai {
  class Strategy;
}

#include "AI.h"
#include "state/Room.h"
#include "Strategy.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Operations
  public:
    std::vector<std::string> run (std::vector<std::string>& list);
    HeuristicAI ();
    HeuristicAI (state::State* state);
    ~HeuristicAI ();
    // Setters and Getters
  };

};

#endif
