// Generated by dia2code
#ifndef AI__NOEUD__H
#define AI__NOEUD__H

#include <vector>

namespace ai {
  class Noeud;
};
namespace state {
  class Character;
  class Team;
  class State;
}

#include "state/Character.h"
#include "state/Team.h"
#include "state/State.h"

namespace ai {

  /// class Noeud - 
  class Noeud {
    // Associations
    // Attributes
  public:
    Noeud* parent     = nullptr;
    std::vector<Noeud*> children;
    int etage;
    std::pair<state::Team*,int> data;
    bool istete;
    // Operations
  public:
    Noeud (std::pair<state::Team*,int> data);
    Noeud (std::pair<state::Team*,int> data, int etage, Noeud* parent, Noeud* tete);
    ~Noeud ();
    std::pair<state::Team*,int> recherchedata_ite (Noeud* noeud, Noeud* tete);
    std::pair<Noeud*,int> rechercheloc_ite (Noeud* noeud, Noeud* tete);
    void inserer (Noeud* noeud);
    Noeud* getParent ();
    std::vector<Noeud*> getChildren ();
    int getEtage ();
    std::pair<state::Team*,int> getData ();
    bool getIsTete ();
    // Setters and Getters
  };

};

#endif
