// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <random>
#include <string>
#include <vector>

namespace engine {
  class Engine;
};
namespace state {
  class State;
};
namespace ai {
  class AI;
};
namespace state {
  class Room;
}

#include "AI.h"
#include "state/Room.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Associations
    // Attributes
  private:
    std::mt19937 randgen;
    // Operations
  public:
    std::vector<std::string> run (std::vector<std::string>& list);
    RandomAI ();
    RandomAI (engine::Engine* engine, state::State* state);
    ~RandomAI ();
    // Setters and Getters
  };

};

#endif
