// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <random>
#include <string>
#include <vector>

namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Attributes
  private:
    std::mt19937 randgen;
    // Operations
  public:
    std::string run (std::vector<std::string>& list);
    RandomAI ();
    ~RandomAI ();
    // Setters and Getters
  };

};

#endif
