// Generated by dia2code
#ifndef AI__STRATEGY__H
#define AI__STRATEGY__H


namespace state {
  class Character;
  class Team;
  class State;
}

#include "state/State.h"
#include "state/Team.h"
#include "state/Character.h"

namespace ai {

  /// class Strategy - 
  class Strategy {
    // Associations
    // Attributes
  private:
    state::Character* firstAdv;
    state::Character* cibleDef;
    state::Character* cibleLife;
    int lifeAdv;
    state::Character* lifeMin;
    state::Team* team;
    // Operations
  public:
    Strategy (state::Team* team, state::State* state);
    ~Strategy ();
    state::Team* getTeam ( );
    void setTeam (state::Team* team);
    int getLifeAdv ();
    void setLifeAdv (int lifeAdv);
    state::Character* getCibleLife ();
    void setCibleLife (state::Character* cibleLife);
    state::Character* getCibleDef ();
    void setCibleDef (state::Character* cibleDef);
    state::Character* getFirst ( );
    void setFirst (state::Character* firstAdv);
    state::Character* getLifeMin ();
    void setLifeMin (state::Character* lifeMin);
    // Setters and Getters
  };

};

#endif
