// Generated by dia2code
#ifndef ENGINE__CHANGEACTIVECOMMAND__H
#define ENGINE__CHANGEACTIVECOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class ChangeActiveCommand - 
  class ChangeActiveCommand : public engine::Command {
    // Operations
  public:
    ChangeActiveCommand ();
    ~ChangeActiveCommand ();
    CommandTypeId getCommandTypeId ();
    void execute (state::State* state);
    // Setters and Getters
  };

};

#endif
