// Generated by dia2code
#ifndef ENGINE__CHOOSEDUNGEONCOMMAND__H
#define ENGINE__CHOOSEDUNGEONCOMMAND__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class ChooseDungeonCommand - 
  class ChooseDungeonCommand : public engine::Command {
    // Attributes
  private:
    std::string chosenDungeon;
    // Operations
  public:
    ChooseDungeonCommand ();
    ~ChooseDungeonCommand ();
    CommandTypeId getCommandTypeId ();
    void execute (state::State* state);
    std::string getChosenDungeon ();
    std::string setChosenDungeon ();
    // Setters and Getters
  };

};

#endif
