// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    CreateDungeon     = 0,
    ChooseDungeon     = 1,
    CreateRoom     = 2,
    CreateVillage     = 3,
    UseSkill     = 4,
    UseItem     = 5,
    ChangeActive     = 6
  };

};

#endif
