// Generated by dia2code
#ifndef ENGINE__CRAETEROOMCOMMAND__H
#define ENGINE__CRAETEROOMCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CraeteRoomCommand - 
  class CraeteRoomCommand : public engine::Command {
    // Operations
  public:
    CraeteRoomCommand ();
    ~CraeteRoomCommand ();
    CommandTypeId getCommandTypeId ();
    void execute (state::State* state);
    // Setters and Getters
  };

};

#endif
