// Generated by dia2code
#ifndef ENGINE__CRAETEDUNGEONCOMMAND__H
#define ENGINE__CRAETEDUNGEONCOMMAND__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CraeteDungeonCommand - 
  class CraeteDungeonCommand : public engine::Command {
    // Attributes
  private:
    std::string dungeonListfile     = "res/Dungeons/DungeonList.txt";
    // Operations
  public:
    CraeteDungeonCommand ();
    ~CraeteDungeonCommand ();
    CommandTypeId getCommandTypeId ();
    void execute (state::State* state);
    // Setters and Getters
  };

};

#endif
