// Generated by dia2code
#ifndef ENGINE__CREATEVILLAGECOMMAND__H
#define ENGINE__CREATEVILLAGECOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CreateVillageCommand - 
  class CreateVillageCommand : public engine::Command {
    // Operations
  public:
    CreateVillageCommand ();
    ~CreateVillageCommand ();
    CommandTypeId getCommandTypeId ();
    void execute (state::State* state);
    // Setters and Getters
  };

};

#endif
