// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <map>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  public:
    state::State* currentState;
    std::map<int,Command*> currentCommands;
    // Operations
  public:
    Engine ();
    Engine (state::State* state);
    ~Engine ();
    state::State* getState ();
    void addPassiveCommands ();
    void addCommand (int priority, Command* cmd);
    void update ();
    // Setters and Getters
  };

};

#endif
