// Generated by dia2code
#ifndef ENGINE__USESKILLCOMMAND__H
#define ENGINE__USESKILLCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class UseSkillCommand - 
  class UseSkillCommand : public engine::Command {
    // Operations
  public:
    UseSkillCommand ();
    ~UseSkillCommand ();
    CommandTypeId getCommandTypeId ();
    void execute (state::State* state);
    // Setters and Getters
  };

};

#endif
