// Generated by dia2code
#ifndef SERVER__COMMANDSERVICE__H
#define SERVER__COMMANDSERVICE__H

#include <map>
#include <json/json.h>

namespace server {
  class AbstractService;
  class Command;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "Command.h"

namespace server {

  /// class CommandService - 
  class CommandService : public server::AbstractService {
    // Associations
    // Attributes
  protected:
    std::map<int,Command*> commandMap;
    // Operations
  public:
    CommandService ();
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus getAll (Json::Value& out) const;
    HttpStatus post (const Json::Value& in, int id);
    HttpStatus remove (int id);
    HttpStatus put (Json::Value out, const Json::Value& in);
    // Setters and Getters
    const std::map<int,Command*>& getCommandMap() const;
    void setCommandMap(const std::map<int,Command*>& commandMap);
  };

};

#endif
