// Generated by dia2code
#ifndef SERVER__COMMAND__H
#define SERVER__COMMAND__H

#include <string>

namespace server {

  /// class Command - 
  class Command {
    // Attributes
  public:
    int id;
    std::string param1;
    std::string param2;
    // Operations
  public:
    Command (int id, std::string param1, std::string param2);
    // Setters and Getters
  };

};

#endif
